# Generated by Django 5.2.8 on 2025-12-03 04:11

import academy.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('btn_text', models.CharField(default='Ver más', max_length=50, verbose_name='Texto del Botón')),
                ('btn_url', models.CharField(default='#', max_length=200, verbose_name='Enlace del Botón')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='Imagen Decorativa')),
                ('style', models.CharField(choices=[('primary', 'Azul Brillante'), ('dark', 'Azul Oscuro'), ('gradient', 'Gradiente')], default='primary', max_length=20, verbose_name='Estilo de Fondo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tarjeta de Anuncio',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome class or similar', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CertificationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(default='Certificado Profesional', max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('icon_class', models.CharField(default='fab fa-microsoft', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('reviews_count', models.IntegerField(default=100)),
                ('style', models.CharField(choices=[('blue', 'Azul'), ('indigo', 'Indigo'), ('green', 'Verde')], default='blue', max_length=20)),
                ('url', models.CharField(default='#', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarjeta de Certificación',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('start_date', models.DateTimeField(verbose_name='Inicio del Evento')),
                ('end_date', models.DateTimeField(verbose_name='Fin del Evento')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación Principal')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='Capacidad Máxima (Aforo)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Entrada')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Imagen del Evento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Soporta HTML', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('style', models.CharField(choices=[('promo', 'Estilo Promo'), ('business', 'Estilo Negocios'), ('new', 'Estilo Lanzamiento')], default='promo', max_length=20)),
                ('tag_text', models.CharField(blank=True, max_length=50)),
                ('btn1_text', models.CharField(default='Ver más', max_length=50)),
                ('btn1_url', models.CharField(default='#', max_length=200)),
                ('btn2_text', models.CharField(blank=True, max_length=50)),
                ('btn2_url', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slide del Home',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Institución')),
                ('logo', models.ImageField(upload_to='institutions/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('video', 'Video (YouTube/Vimeo)'), ('article', 'Artículo / Lectura'), ('pdf', 'Documento PDF'), ('resource', 'Recurso Descargable (ZIP/Excel/Etc)'), ('assignment', 'Tarea / Asignación')], default='video', max_length=20, verbose_name='Tipo de Lección')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL del Video')),
                ('content', models.TextField(blank=True, verbose_name='Contenido / Descripción')),
                ('file', models.FileField(blank=True, null=True, upload_to='lessons/files/', validators=[academy.validators.validate_file_extension], verbose_name='Archivo Adjunto')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in minutes')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Banco/Método')),
                ('account_info', models.CharField(max_length=200, verbose_name='Información de Cuenta/Celular')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='payment_qrs/', verbose_name='Código QR')),
                ('instructions', models.TextField(verbose_name='Instrucciones Adicionales')),
                ('color', models.CharField(default='blue', help_text='Color para el botón (ej: purple, green, blue)', max_length=20, verbose_name='Color de Identidad')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('single_choice', 'Opción Múltiple (Una respuesta)'), ('multiple_choice', 'Opción Múltiple (Varias respuestas)'), ('true_false', 'Verdadero / Falso'), ('short_answer', 'Respuesta Corta'), ('matching', 'Relacionar Columnas'), ('ordering', 'Ordenamiento / Secuencia')], default='single_choice', max_length=20)),
                ('points', models.FloatField(default=1.0)),
                ('explanation', models.TextField(blank=True, help_text='Explicación que se muestra después de responder')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LMS Academy', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_config/')),
                ('logo_width', models.PositiveIntegerField(default=40)),
                ('logo_height', models.PositiveIntegerField(default=40)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('sub_message', models.CharField(blank=True, max_length=200)),
                ('btn_text', models.CharField(blank=True, max_length=50)),
                ('btn_url', models.CharField(blank=True, max_length=200)),
                ('style', models.CharField(choices=[('cyber', 'Cyber'), ('black_friday', 'Black Friday'), ('info', 'Info'), ('warning', 'Alerta')], default='cyber', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Barra de Anuncio Top',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('course_type', models.CharField(choices=[('course', 'Curso Grabado'), ('seminar', 'Seminario en Vivo')], default='course', max_length=20, verbose_name='Tipo de Producto')),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('learning_objectives', models.TextField(blank=True, verbose_name='Lo que aprenderás (un punto por línea)')),
                ('requirements', models.TextField(blank=True, verbose_name='Requisitos (un punto por línea)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('preview_video_url', models.URLField(blank=True, null=True, verbose_name='Video de Vista Previa (YouTube)')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio (Seminarios)')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin (Opcional)')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='Enlace de Zoom/YouTube Live')),
                ('launch_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lanzamiento (Cuenta Regresiva)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Actual (Oferta)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Normal (Sin descuento)')),
                ('allow_monthly_payment', models.BooleanField(default=False, verbose_name='¿Permitir Pago Mensual?')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio Mensual')),
                ('duration_months', models.PositiveIntegerField(default=1, verbose_name='Duración en Meses')),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academy.category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academy.institution', verbose_name='Institución que Respalda')),
                ('allowed_payment_methods', models.ManyToManyField(blank=True, related_name='courses', to='academy.paymentmethod', verbose_name='Métodos de Pago Aceptados')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Pago'), ('review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('selected_payment_plan', models.CharField(choices=[('full', 'Pago Completo'), ('monthly', 'Mensualidad')], default='full', max_length=20)),
                ('installments_paid', models.PositiveIntegerField(default=0, verbose_name='Cuotas Pagadas')),
                ('voucher_image', models.ImageField(blank=True, null=True, upload_to='vouchers/', verbose_name='Constancia de Pago')),
                ('is_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academy.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Sesión')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_time', models.DateTimeField(verbose_name='Hora Inicio')),
                ('end_time', models.DateTimeField(verbose_name='Hora Fin')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Sala / Ambiente')),
                ('session_type', models.CharField(choices=[('workshop', 'Taller Práctico'), ('lecture', 'Conferencia'), ('break', 'Receso/Almuerzo'), ('networking', 'Networking')], default='lecture', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academy.event')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_speaking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Agenda',
                'verbose_name_plural': 'Agenda del Evento',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Tema')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_topics', to='academy.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='academy.forumtopic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='academy.lesson')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='academy.lessoncomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academy.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academy.module'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('reply', 'Respuesta'), ('grade', 'Nota'), ('system', 'Sistema')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Profesor')], default='student', max_length=20)),
                ('dni', models.CharField(blank=True, help_text='DNI de 8 dígitos', max_length=8)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('academic_profile', models.CharField(choices=[('student', 'Estudiante'), ('graduate', 'Egresado'), ('professional', 'Profesional')], default='student', max_length=20, verbose_name='Perfil Académico')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino')], max_length=10, verbose_name='Género')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Número de Celular')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('match_text', models.CharField(blank=True, help_text='Texto correspondiente para relacionar (Columna B)', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden correcto para preguntas de secuencia')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academy.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('pass_mark', models.IntegerField(default=70)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duración en minutos (0 para sin límite)')),
                ('randomize_questions', models.BooleanField(default=False, verbose_name='¿Aleatorizar preguntas?')),
                ('questions_to_show', models.PositiveIntegerField(default=10, help_text='Número de preguntas a mostrar (si es aleatorio)')),
                ('is_final_exam', models.BooleanField(default=False, verbose_name='¿Es examen final?')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='academy.module')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academy.quiz'),
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('passed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quizzes', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.FloatField(default=0.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.question')),
                ('selected_answers', models.ManyToManyField(blank=True, to='academy.answer')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academy.quizsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Número de Cuota')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('voucher_image', models.ImageField(blank=True, null=True, upload_to='vouchers/installments/', verbose_name='Comprobante')),
                ('feedback', models.TextField(blank=True, verbose_name='Observaciones')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='academy.enrollment')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['installment_number'],
                'unique_together': {('enrollment', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_text', models.TextField(blank=True, verbose_name='Texto de la Tarea')),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignments/', validators=[academy.validators.validate_file_extension], verbose_name='Archivo de la Tarea')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota')),
                ('instructor_feedback', models.TextField(blank=True, verbose_name='Feedback del Instructor')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='academy.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Usado / Asistió')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='academy.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
