# Generated by Django 5.2.8 on 2025-11-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Pago'), ('review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='voucher_image',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/', verbose_name='Constancia de Pago'),
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_profile',
            field=models.CharField(choices=[('student', 'Estudiante'), ('graduate', 'Egresado'), ('professional', 'Profesional')], default='student', max_length=20, verbose_name='Perfil Académico'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dni',
            field=models.CharField(blank=True, help_text='DNI de 8 dígitos', max_length=8),
        ),
    ]
