# Generated by Django 5.2.8 on 2025-11-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_enrollment_is_completed_enrollment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(default='Certificado Profesional', max_length=100)),
                ('provider', models.CharField(help_text='Ej: Microsoft', max_length=50)),
                ('icon_class', models.CharField(default='fab fa-microsoft', help_text='Clase de FontAwesome', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('reviews_count', models.IntegerField(default=100)),
                ('style', models.CharField(choices=[('blue', 'Azul (Microsoft style)'), ('indigo', 'Indigo (IBM style)'), ('green', 'Verde (Google style)')], default='blue', max_length=20)),
                ('url', models.CharField(default='#', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarjeta de Certificación',
                'verbose_name_plural': 'Tarjetas de Certificación',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Soporta HTML básico (ej: <span>...</span>)', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('style', models.CharField(choices=[('promo', 'Estilo Promo (Gold/Black)'), ('business', 'Estilo Negocios (Blue)'), ('new', 'Estilo Lanzamiento (Purple/Neon)')], default='promo', max_length=20)),
                ('tag_text', models.CharField(blank=True, help_text='Ej: Oferta Limitada', max_length=50)),
                ('btn1_text', models.CharField(default='Ver más', max_length=50)),
                ('btn1_url', models.CharField(default='#', max_length=200)),
                ('btn2_text', models.CharField(blank=True, help_text="Solo para estilo 'Lanzamiento'", max_length=50)),
                ('btn2_url', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slide del Home',
                'verbose_name_plural': 'Slides del Home',
                'ordering': ['order'],
            },
        ),
    ]
