# Generated by Django 5.2.8 on 2025-12-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_event_organizer_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook_url",
            field=models.URLField(blank=True, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, verbose_name="Sitio Web"),
        ),
    ]
