# Generated by Django 5.2.8 on 2025-12-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0003_profile_facebook_url_profile_website"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
    ]
