# Generated by Django 5.2.8 on 2025-11-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_certificationcard_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/files/', verbose_name='Archivo Adjunto'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video (YouTube/Vimeo)'), ('article', 'Artículo / Lectura'), ('pdf', 'Documento PDF'), ('resource', 'Recurso Descargable (ZIP/Excel/Etc)')], default='video', max_length=20, verbose_name='Tipo de Lección'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenido / Descripción'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del Video'),
        ),
    ]
