# Generated by Django 5.2.8 on 2025-12-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0004_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Monto Pagado"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente de Pago"),
                    ("review", "En Revisión"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="voucher_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="vouchers/tickets/",
                verbose_name="Constancia de Pago",
            ),
        ),
    ]
