# Generated by Django 5.2.8 on 2025-11-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_lessoncomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="preview_video_url",
            field=models.URLField(
                blank=True,
                null=True,
                verbose_name="Video de Vista Previa (YouTube/Vimeo)",
            ),
        ),
    ]
