# Generated by Django 5.2.8 on 2025-12-12 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_ticket_amount_paid_ticket_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Tipo (ej: VIP)"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Cantidad Disponible"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="academy.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="academy.tickettier",
            ),
        ),
    ]
