# Generated by Django 5.2.8 on 2025-12-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0006_tickettier_ticket_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="academy.tickettier",
            ),
        ),
    ]
