# Generated by Django 5.2.8 on 2025-11-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0006_course_preview_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview_video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Video de Vista Previa (YouTube)"
            ),
        ),
    ]
