# Generated by Django 5.2.8 on 2025-11-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0007_alter_course_preview_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="due_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Entrega"
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="assignment_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assignments/",
                verbose_name="Archivo de la Tarea",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="assignment_text",
            field=models.TextField(blank=True, verbose_name="Texto de la Tarea"),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="instructor_feedback",
            field=models.TextField(blank=True, verbose_name="Feedback del Instructor"),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Nota",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("video", "Video (YouTube/Vimeo)"),
                    ("article", "Artículo / Lectura"),
                    ("pdf", "Documento PDF"),
                    ("resource", "Recurso Descargable (ZIP/Excel/Etc)"),
                    ("assignment", "Tarea / Asignación"),
                ],
                default="video",
                max_length=20,
                verbose_name="Tipo de Lección",
            ),
        ),
    ]
