# Generated by Django 5.2.8 on 2025-12-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0007_alter_ticket_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="attendee_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email Asistente"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="attendee_first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nombre Asistente"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="attendee_last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Apellido Asistente"
            ),
        ),
    ]
