# Generated by Django 5.2.8 on 2025-11-28 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0008_lesson_due_date_lessonprogress_assignment_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True, help_text="Explicación que se muestra después de responder"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "Opción Múltiple (Una respuesta)"),
                    ("multiple_choice", "Opción Múltiple (Varias respuestas)"),
                    ("true_false", "Verdadero / Falso"),
                    ("short_answer", "Respuesta Corta"),
                ],
                default="single_choice",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AddField(
            model_name="quizsubmission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quizsubmission",
            name="teacher_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_answer", models.TextField(blank=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("points_awarded", models.FloatField(default=0.0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academy.question",
                    ),
                ),
                (
                    "selected_answers",
                    models.ManyToManyField(blank=True, to="academy.answer"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="academy.quizsubmission",
                    ),
                ),
            ],
        ),
    ]
