# Generated by Django 5.2.8 on 2025-11-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0009_alter_question_options_question_explanation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="answer",
            name="match_text",
            field=models.CharField(
                blank=True,
                help_text="Texto correspondiente para relacionar (Columna B)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Orden correcto para preguntas de secuencia"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "Opción Múltiple (Una respuesta)"),
                    ("multiple_choice", "Opción Múltiple (Varias respuestas)"),
                    ("true_false", "Verdadero / Falso"),
                    ("short_answer", "Respuesta Corta"),
                    ("matching", "Relacionar Columnas"),
                    ("ordering", "Ordenamiento / Secuencia"),
                ],
                default="single_choice",
                max_length=20,
            ),
        ),
    ]
