# Generated by Django 5.2.8 on 2025-11-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_answer_options_answer_match_text_answer_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Normal (Sin descuento)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Actual (Oferta)'),
        ),
    ]
