# Generated by Django 5.2.8 on 2025-11-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0011_course_old_price_alter_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="duration",
            field=models.PositiveIntegerField(
                default=0, help_text="Duración en minutos (0 para sin límite)"
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_final_exam",
            field=models.BooleanField(default=False, verbose_name="¿Es examen final?"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions_to_show",
            field=models.PositiveIntegerField(
                default=10, help_text="Número de preguntas a mostrar (si es aleatorio)"
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="randomize_questions",
            field=models.BooleanField(
                default=False, verbose_name="¿Aleatorizar preguntas?"
            ),
        ),
    ]
