# Generated by Django 5.2.8 on 2025-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0012_quiz_duration_quiz_is_final_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Masculino"), ("female", "Femenino")],
                max_length=10,
                verbose_name="Género",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Número de Celular"
            ),
        ),
    ]
