# Generated by Django 5.2.8 on 2025-11-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_profile_gender_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
