# Generated by Django 5.2.8 on 2025-11-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('btn_text', models.CharField(default='Ver más', max_length=50, verbose_name='Texto del Botón')),
                ('btn_url', models.CharField(default='#', max_length=200, verbose_name='Enlace del Botón')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='Imagen Decorativa')),
                ('style', models.CharField(choices=[('primary', 'Azul Brillante (Estilo Plus)'), ('dark', 'Azul Oscuro (Estilo Business)'), ('gradient', 'Gradiente (Estilo Especial)')], default='primary', max_length=20, verbose_name='Estilo de Fondo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tarjeta de Anuncio',
                'verbose_name_plural': 'Tarjetas de Anuncios',
                'ordering': ['order'],
            },
        ),
    ]
