# Generated by Django 5.2.8 on 2025-11-29 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_forumtopic_forumreply_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Institución')),
                ('logo', models.ImageField(upload_to='institutions/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academy.institution', verbose_name='Institución que Respalda'),
        ),
    ]
