# Generated by Django 5.2.8 on 2025-11-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0017_institution_course_institution"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Banco/Método"
                    ),
                ),
                (
                    "account_info",
                    models.CharField(
                        max_length=200, verbose_name="Información de Cuenta/Celular"
                    ),
                ),
                (
                    "qr_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="payment_qrs/",
                        verbose_name="Código QR",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(verbose_name="Instrucciones Adicionales"),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue",
                        help_text="Color para el botón (ej: purple, green, blue)",
                        max_length=20,
                        verbose_name="Color de Identidad",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[("course", "Curso Grabado"), ("seminar", "Seminario en Vivo")],
                default="course",
                max_length=20,
                verbose_name="Tipo de Producto",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Fin (Opcional)"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="live_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Enlace de Zoom/YouTube Live"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Inicio (Seminarios)"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="allowed_payment_methods",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="academy.paymentmethod",
                verbose_name="Métodos de Pago Aceptados",
            ),
        ),
    ]
