# Generated by Django 5.2.8 on 2025-11-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0018_paymentmethod_course_course_type_course_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="launch_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Fecha de Lanzamiento (Cuenta Regresiva)",
            ),
        ),
    ]
