# Generated by Django 5.2.8 on 2025-11-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_course_launch_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Mensaje Principal')),
                ('sub_message', models.CharField(blank=True, max_length=200, verbose_name='Texto Secundario (Opcional)')),
                ('btn_text', models.CharField(blank=True, max_length=50, verbose_name='Texto del Botón')),
                ('btn_url', models.CharField(blank=True, max_length=200, verbose_name='Enlace (URL)')),
                ('style', models.CharField(choices=[('cyber', 'Cyber/Neon (Morado/Verde)'), ('black_friday', 'Black Friday (Negro/Rojo)'), ('info', 'Informativo (Azul/Indigo)'), ('warning', 'Alerta (Naranja)')], default='cyber', max_length=20)),
                ('is_active', models.BooleanField(default=False, verbose_name='¿Mostrar barra?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Barra de Anuncio Top',
                'verbose_name_plural': 'Barras de Anuncio',
            },
        ),
    ]
