# Generated by Django 5.2.8 on 2025-11-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0020_topbanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="allow_monthly_payment",
            field=models.BooleanField(
                default=False, verbose_name="¿Permitir Pago Mensual?"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_months",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Duración en Meses"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="monthly_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Precio Mensual",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="installments_paid",
            field=models.PositiveIntegerField(default=0, verbose_name="Cuotas Pagadas"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="selected_payment_plan",
            field=models.CharField(
                choices=[("full", "Pago Completo"), ("monthly", "Mensualidad")],
                default="full",
                max_length=20,
            ),
        ),
    ]
