# Generated by Django 5.2.8 on 2025-11-30 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academy",
            "0021_course_allow_monthly_payment_course_duration_months_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveIntegerField(verbose_name="Número de Cuota"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Fecha de Vencimiento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("review", "En Revisión"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "voucher_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vouchers/installments/",
                        verbose_name="Comprobante",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Pago"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="academy.enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuota",
                "verbose_name_plural": "Cuotas",
                "ordering": ["installment_number"],
                "unique_together": {("enrollment", "installment_number")},
            },
        ),
    ]
