# Generated by Django 5.2.8 on 2025-12-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0022_installment"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="LMS Academy",
                        max_length=100,
                        verbose_name="Nombre del Sitio",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site_config/",
                        verbose_name="Logo del Sitio",
                    ),
                ),
                (
                    "logo_width",
                    models.PositiveIntegerField(
                        default=40,
                        help_text="Ancho en píxeles (ej: 128)",
                        verbose_name="Ancho del Logo (px)",
                    ),
                ),
                (
                    "logo_height",
                    models.PositiveIntegerField(
                        default=40,
                        help_text="Alto en píxeles (ej: 128)",
                        verbose_name="Alto del Logo (px)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sitio",
                "verbose_name_plural": "Configuración del Sitio",
            },
        ),
    ]
