# Generated by Django 5.2.8 on 2025-12-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0023_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio Mensual'),
        ),
    ]
