# Generated by Django 5.2.8 on 2025-12-01 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0025_usersession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Título del Evento"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(verbose_name="Descripción")),
                ("date", models.DateTimeField(verbose_name="Fecha y Hora")),
                (
                    "location",
                    models.CharField(
                        max_length=200, verbose_name="Ubicación (Dirección o Link)"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Capacidad Máxima"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Precio de Entrada",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/",
                        verbose_name="Imagen del Evento",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Empresa"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=200, verbose_name="Nombre de Contacto"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo Electrónico"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Teléfono")),
                ("message", models.TextField(verbose_name="Mensaje / Requerimiento")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_handled",
                    models.BooleanField(default=False, verbose_name="Atendido"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Usado / Asistió"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="academy.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "event")},
            },
        ),
    ]
