# Generated by Django 5.2.8 on 2025-12-02 03:53

import academy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0026_event_servicerequest_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("published", "Publicado"),
                    ("archived", "Archivado"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lessons/files/",
                validators=[academy.validators.validate_file_extension],
                verbose_name="Archivo Adjunto",
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="assignment_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assignments/",
                validators=[academy.validators.validate_file_extension],
                verbose_name="Archivo de la Tarea",
            ),
        ),
    ]
