# Generated by Django 5.2.8 on 2025-12-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0027_course_status_alter_lesson_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="learning_objectives",
            field=models.TextField(
                blank=True, verbose_name="Lo que aprenderás (un punto por línea)"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements",
            field=models.TextField(
                blank=True, verbose_name="Requisitos (un punto por línea)"
            ),
        ),
    ]
