# Generated by Django 5.2.8 on 2025-12-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0028_course_learning_objectives_course_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente de Pago"),
                    ("review", "En Revisión"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="voucher_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="event_vouchers/",
                verbose_name="Constancia de Pago",
            ),
        ),
    ]
